---
title: 컴파일러 오류 CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: 7ea5e861b71f5f65231bb29537a28a23a0821cef
ms.sourcegitcommit: 10986410e59ff29f2ec55c6759bde3eb4d1a00cb
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 05/31/2019
ms.locfileid: "66422968"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="2a1ef-102">컴파일러 오류 CS0156</span><span class="sxs-lookup"><span data-stu-id="2a1ef-102">Compiler Error CS0156</span></span>
<span data-ttu-id="2a1ef-103">바로 바깥쪽 catch 절에 중첩된 finally 절에는 인수가 없는 throw 문을 사용할 수 없습니다.</span><span class="sxs-lookup"><span data-stu-id="2a1ef-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="2a1ef-104">매개 변수가 없는 [throw](../../csharp/language-reference/keywords/throw.md) 문은 매개 변수를 사용하지 않는 **catch** 절에서만 나타날 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="2a1ef-104">A [throw](../../csharp/language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="2a1ef-105">자세한 내용은 [예외 및 예외 처리](../../csharp/programming-guide/exceptions/index.md)합니다.</span><span class="sxs-lookup"><span data-stu-id="2a1ef-105">For more information, see [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="2a1ef-106">다음 샘플에서는 CS0156을 생성합니다.</span><span class="sxs-lookup"><span data-stu-id="2a1ef-106">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
