---
title: "&#39; Throw&#39; 문 외부에서 피연산자를 생략할 수 없습니다는 &#39; Catch &#39; 문 또는 내부는 &#39; 마지막으로 &#39; 문"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a><span data-ttu-id="c3c0a-102">&#39; Throw&#39; 문 외부에서 피연산자를 생략할 수 없습니다는 &#39; Catch &#39; 문 또는 내부는 &#39; 마지막으로 &#39; 문</span><span class="sxs-lookup"><span data-stu-id="c3c0a-102">&#39;Throw&#39; statement cannot omit operand outside a &#39;Catch&#39; statement or inside a &#39;Finally&#39; statement</span></span>
<span data-ttu-id="c3c0a-103">`Throw` 문 외부의 `Catch` 문에서 예외 개체의 이름을 제공해야 합니다.</span><span class="sxs-lookup"><span data-stu-id="c3c0a-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="c3c0a-104">**오류 ID:** BC30666</span><span class="sxs-lookup"><span data-stu-id="c3c0a-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="c3c0a-105">이 오류를 해결하려면</span><span class="sxs-lookup"><span data-stu-id="c3c0a-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="c3c0a-106">`System.Exception`에서 파생된 예외 개체의 이름을 지정합니다.</span><span class="sxs-lookup"><span data-stu-id="c3c0a-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="c3c0a-107">`Throw` 문이 `Catch` 블록 내부에 있도록 코드를 재구성합니다.</span><span class="sxs-lookup"><span data-stu-id="c3c0a-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="c3c0a-108">참고 항목</span><span class="sxs-lookup"><span data-stu-id="c3c0a-108">See Also</span></span>  
 [<span data-ttu-id="c3c0a-109">Throw 문</span><span class="sxs-lookup"><span data-stu-id="c3c0a-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)  
 [<span data-ttu-id="c3c0a-110">Try...Catch...Finally 문</span><span class="sxs-lookup"><span data-stu-id="c3c0a-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [<span data-ttu-id="c3c0a-111">Visual Basic의 예외 클래스</span><span class="sxs-lookup"><span data-stu-id="c3c0a-111">Exception Class in Visual Basic</span></span>](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [<span data-ttu-id="c3c0a-112">예외 및 Visual Basic에서의 오류 처리</span><span class="sxs-lookup"><span data-stu-id="c3c0a-112">Exception and Error Handling in Visual Basic</span></span>](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
