---
title: "'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: d07afdb2c6026028e765173b87e869aedb0d3155
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53763541"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다.
`Exit Try`는 `Try` 블록 문에서만 나올 수 있습니다. 중복 `Exit Try` 문이 있거나 또는 `Exit Try` 문이 해당 `Try` 블록의 경계를 벗어난 곳에 나타납니다.  
  
 **오류 ID:** BC30393  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  불필요한 `Exit Try` 문을 찾아서 제거합니다.  
  
2.  이동 된 `Exit Try` 코드 내에서 적절 한 위치로 문입니다.  
  
## <a name="see-also"></a>참고 항목  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
