---
title: "&quot;Catch&quot; 블록에에 도달할 때문에 &quot;&lt;name1&gt;&quot;에서 상속&quot;&lt;name2&gt;&quot; | Microsoft 문서"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 12
author: dotnet-bot
ms.author: dotnetcontent
translation.priority.ht:
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- ru-ru
- zh-cn
- zh-tw
translation.priority.mt:
- cs-cz
- pl-pl
- pt-br
- tr-tr
translationtype: Machine Translation
ms.sourcegitcommit: a06bd2a17f1d6c7308fa6337c866c1ca2e7281c0
ms.openlocfilehash: 2c7f180b2221b5aa6814629a5a8cd9b9d7f9fb1b
ms.lasthandoff: 03/13/2017

---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>'Catch' 블록에에 도달할 때문에 '&lt;name1&gt;'에서 상속'&lt;name2&gt;'
코드 내의 `Catch` 블록에 도달하지 않습니다.  
  
 이 메시지는 기본적으로 경고입니다. 경고를 숨기 거 나 경고를 오류로 처리에 대 한 자세한 내용은 참조 하십시오. [Visual Basic에서 경고 구성](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic)합니다.  
  
 **오류 ID:** BC42029  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
-   불필요한 `Catch` 블록을 제거합니다.  
  
## <a name="see-also"></a>참고 항목  
 [방법: 테스트 코드를 try... Visual Basic의 catch 블록](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
