---
title: "&#39; Catch &#39; 블록에 도달 하지 않습니다, 때문에 &#39; &lt;name1&gt;&#39;에서 상속 &#39;&lt; name2&gt;&#39;"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 699f2ef1ff9d554bb9203631017b424ab887ab93
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 01/19/2018
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39; Catch &#39; 블록에 도달 하지 않습니다, 때문에 &#39; &lt;name1&gt;&#39;에서 상속 &#39;&lt; name2&gt;&#39;
코드 내의 `Catch` 블록에 도달하지 않습니다.  
  
 이 메시지는 기본적으로 경고입니다. 경고를 숨기 거 나 경고를 오류로 처리 하는 방법에 대 한 자세한 내용은 참조 하십시오. [Visual Basic에서 경고 구성](/visualstudio/ide/configuring-warnings-in-visual-basic)합니다.  
  
 **오류 ID:** BC42029  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
-   불필요한 `Catch` 블록을 제거합니다.  
  
## <a name="see-also"></a>참고 항목  
 [방법: 테스트 코드를 try... Visual Basic의 catch 블록](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
